# Application Config
baseUrl=https://automationexercise.com
browser=chrome
gridUrl=http://localhost:4444
# Valid Login Credentials
validEmail=kotianbs4@gmail.com
validPassword=Test@123

# Invalid Credentials
invalidEmail=wrongemail@gmail.com
invalidPassword=wrongpass

# Environment
environment=QA

# Timeouts
implicitWait=10
explicitWait=30